#!/usr/bin/bash

echo "[+] This script adds the kali rolling repository to your Deb system."
echo "[!] Note this script must be run with sudo privileges!"

if [[ $(id -u) -ne 0 ]]; then
    echo "[!] You must be root or have root permissions to run this script."
    exit 1
else
    echo "[?] Do you wish to install this program?"
    select yn in "Yes" "No"; do
        case $yn in
            "Yes" )
                echo 'Adding Kali repsistory...'  
                echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list 
                wget 'https://archive.kali.org/archive-key.asc'
                if apt-key add archive-key.asc; then
                    echo 'Package: *'>/etc/apt/preferences.d/kali.pref
                    echo 'Pin: release a=kali-rolling'>>/etc/apt/preferences.d/kali.pref
                    echo 'Pin-Priority: 50'>>/etc/apt/preferences.d/kali.pref
                    apt update -y
                    apt install -f
                    echo '[+] The repo was added successfully!'
                    echo '[+] you should run sudo apt update && sudo apt upgrade to ensure the package lists are properly updated'
                else 
                    echo '[-] Error: Failed to add the Kali repository key.'
                fi 
                break
                ;;
            "No" ) 
                echo 'Okay! you can use this next time to add the kali apt repository.'
                break
                ;;
        esac
    done
fi